#!/usr/bin/env bash
set -e

echo "==> Docker installeren..."
apt-get update
apt-get install -y ca-certificates curl gnupg jq

# Docker apt keyring en repository slechts één keer configureren
if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
fi

if [ ! -f /etc/apt/sources.list.d/docker.list ]; then
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${VERSION_CODENAME:-$VERSION}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Vagrant user mag docker gebruiken (optioneel, voor niet-sudo)
usermod -aG docker vagrant 2>/dev/null || true

echo "==> NetBox containers starten..."
# Compose verwacht dit bestand (wordt later gevuld met Diode secret)
mkdir -p /vagrant/netbox/env
: > /vagrant/netbox/env/netbox.generated.env
cd /vagrant/netbox
docker compose up -d

echo "==> Wachten tot NetBox bereikbaar is..."
# NetBox doet init + migrations; dat kan even duren (zeker met plugins). Wacht max ~10 min.
ready="false"
for i in $(seq 1 120); do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 http://127.0.0.1:8000/login/ 2>/dev/null || echo 000)"
  if [ "$code" = "200" ]; then
    echo "    NetBox is bereikbaar (HTTP 200 op /login/)."
    ready="true"
    break
  fi
  sleep 5
done

if [ "$ready" != "true" ]; then
  echo "    Waarschuwing: NetBox is na ~10 min nog niet bereikbaar (laatste HTTP code: $code)."
  echo "    Tip: kijk logs met: cd /vagrant/netbox && docker compose logs --tail 80 netbox"
fi

echo "==> Diode installeren en starten..."
# Diode quickstart (idempotent). NetBox URL moet voor Diode containers bereikbaar zijn.
DIODE_DIR="/opt/diode"
NETBOX_URL_FOR_DIODE="http://172.17.0.1:8000"

mkdir -p "$DIODE_DIR"
cd "$DIODE_DIR"

if [ ! -f quickstart.sh ]; then
  curl -sSfLo quickstart.sh https://raw.githubusercontent.com/netboxlabs/diode/release/diode-server/docker/scripts/quickstart.sh
  chmod +x quickstart.sh
fi

if [ ! -f oauth2/client/client-credentials.json ]; then
  ./quickstart.sh "$NETBOX_URL_FOR_DIODE"
fi

docker compose up -d

NETBOX_TO_DIODE_SECRET="$(jq -r '.[] | select(.client_id == "netbox-to-diode") | .client_secret' oauth2/client/client-credentials.json)"
if [ -z "$NETBOX_TO_DIODE_SECRET" ] || [ "$NETBOX_TO_DIODE_SECRET" = "null" ]; then
  echo "    Waarschuwing: kon netbox-to-diode secret niet vinden in $DIODE_DIR/oauth2/client/client-credentials.json"
else
  echo "==> Diode secret injecteren in NetBox env..."
  cat > /vagrant/netbox/env/netbox.generated.env <<EOF
# Generated by Vagrant provisioning (Diode)
DIODE_TARGET_OVERRIDE=grpc://172.17.0.1:8080/diode
NETBOX_TO_DIODE_CLIENT_SECRET=${NETBOX_TO_DIODE_SECRET}
EOF

  # Env-file wijzigingen vereisen recreate van containers
  cd /vagrant/netbox
  docker compose up -d --force-recreate netbox netbox-worker
fi

echo "==> Provisioning klaar."
echo "    NetBox UI in de host-browser:"
echo "      - http://localhost:8000"
echo "      - of via host-only IP: http://192.168.56.10:8000"
